reminder_interval = "3h"

[alerts]
    [alerts.test-alert-1]
    query = """
        SELECT * FROM test_table WHERE test_column > 5
    """
    message = "Something is broken"
    dbs = ["my-postgres-db"]
    destinations = ["slack.my-slack"]
    interval = "10s"
    reminder_interval = "60s"

    [alerts.test-alert-2]
    query = "SELECT 1 as col1, 'hello' as col2"
    message = "Something is broken"
    dbs = ["my-mysql-db"]
    destinations = ["slack.my-slack"]
    interval = "1h30m"


[dbs]
    [dbs.my-postgres-db]
    driver = "postgres"
    connection = "postgres://localhost:5432/postgres?user=postgres&sslmode=disable"


    [dbs.my-mysql-db]
    driver = "mysql"
    connection = "root@/mysql"


[slacks]
    [slacks.my-slack]
    webhook_url = "${MY_SLACK_WEBHOOK}"
